model:
  audio_dim: 128
  text_dim: 128
  num_heads: 4
  num_layers: 4
  vocab_size: 30000
  max_seq_len: 512
  dropout: 0.3
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50
  weight_decay: 0.0001
data:
  dataset_path: ./Dataset
  audio_sample_rate: 16000
  mel_bands: 128